[project]
name = "core"
requires-python = ">=3.10"
dependencies = []

[tool.black]
line-length = 120
exclude = '''^(.*\/migrations\/.*|.*\.venv\/.*|.*\/node_modules\/.*)$'''

[tool.isort]
profile = "black"
line_length = 120
skip = ["migrations", ".venv", "node_modules"]
